export const Cuisines = [
  'African',
  'American',
  'British',
  'Cajun',
  'Caribbean',
  'Chinese',
  'Eastern European',
  'European',
  'French',
  'German',
  'Greek',
  'Indian',
  'Irish',
  'Italian',
  'Japanese',
  'Jewish',
  'Korean',
  'Latin American',
  'Mediterranean',
  'Mexican',
  'Middle Eastern',
  'Nordic',
  'Southern',
  'Spanish',
  'Thai',
  'Vietnamese',
] as const

export const mealTypes = [
  'main course',
  'side dish',
  'dessert',
  'appetizer',
  'salad',
  'bread',
  'breakfast',
  'soup',
  'beverage',
  'sauce',
  'marinade',
  'fingerfood',
  'snack',
  'drink',
] as const

export const sort = [
  'meta-score',
  'popularity',
  'healthiness',
  'price',
  'time',
  'random',
  'max-used-ingredients',
  'min-missing-ingredients',
  'alcohol',
  'caffeine',
  'copper',
  'energy',
  'calories',
  'calcium',
  'carbohydrates',
  'carbs',
  'choline',
  'cholesterol',
  'total-fat',
  'fluoride',
  'trans-fat',
  'saturated-fat',
  'mono-unsaturated-fat',
  'poly-unsaturated-fat',
  'fiber',
  'folate',
  'folic-acid',
  'iodine',
  'iron',
  'magnesium',
  'manganese',
  'vitamin-b3',
  'niacin',
  'vitamin-b5',
  'pantothenic-acid',
  'phosphorus',
  'potassium',
  'protein',
  'vitamin-b2',
  'riboflavin',
  'selenium',
  'sodium',
  'vitamin-b1',
  'thiamin',
  'vitamin-a',
  'vitamin-b6',
  'vitamin-b12',
  'vitamin-c',
  'vitamin-d',
  'vitamin-e',
  'vitamin-k',
  'sugar',
  'zinc',
] as const
